# Generated by Django 4.2.7 on 2024-01-03 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_status_management', '0002_remove_orderprogress_managed_by_and_more'),
        ('checkout', '0002_order_original_bag_order_stripe_pid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='progress',
            field=models.OneToOneField(blank=True, null=False, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='order_status_management.orderprogress'),
        ),
    ]
