# Generated by Django 4.2.7 on 2024-01-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_status_management', '0002_remove_orderprogress_managed_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderprogress',
            name='is_accepted',
        ),
        migrations.RemoveField(
            model_name='orderprogress',
            name='is_being_cooked',
        ),
        migrations.RemoveField(
            model_name='orderprogress',
            name='is_being_delivered',
        ),
        migrations.RemoveField(
            model_name='orderprogress',
            name='is_being_prepared',
        ),
        migrations.RemoveField(
            model_name='orderprogress',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='orderprogress',
            name='new_at',
            field=models.DateTimeField(auto_now_add=True,),
        ),
        migrations.AddField(
            model_name='orderprogress',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('accepted', 'Accepted'), ('being_cooked', 'Being Cooked'), ('being_prepared', 'Being Prepared'), ('being_delivered', 'Being Delivered'), ('completed', 'Completed')], default='new', max_length=20),
        ),
    ]
