# Generated by Django 4.2.7 on 2024-01-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_status_management', '0003_remove_orderprogress_is_accepted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderprogress',
            name='new_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
