# Generated by Django 4.2.7 on 2024-01-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_status_management', '0004_alter_orderprogress_new_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderprogress',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
