# Generated by Django 4.2.7 on 2023-12-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_topping'),
    ]

    operations = [
        migrations.AddField(
            model_name='topping',
            name='category',
            field=models.CharField(choices=[('Meats', 'Meats'), ('Seafood', 'Seafood'), ('Vegetables', 'Vegetables'), ('Fruits', 'Fruits'), ('Cheeses', 'Cheeses'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
