# Generated by Django 4.2.7 on 2024-01-06 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_topping_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
